# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/mihailo-misic/company-resource-api

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      # Getting dependencies
      - run: go get -v -t -d ./...
      - run: go get github.com/mattn/goveralls

      # Testing
      - run: go test -v -cover -race -coverprofile=${TEST_RESULTS}/c.out
      - run:
          name: Run unit tests
          command: |
            trap "goveralls -coverprofile=${TEST_RESULTS}/c.out -service=circle-ci -repotoken=yCn3klc8SDmcBsJmiov4DOGl5gLgdYlGq" EXIT
            make test | tee ${TEST_RESULTS}/c.out
      - run: make

      - store_artifacts:
          path: $TEST_RESULTS
          destination: raw-test-output

      - store_test_results:
          path: $TEST_RESULTS