version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/mihailo-misic/company-resource-api

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      # Getting dependencies
      - run: go get -v -t -d ./...
      - run: go get github.com/mattn/goveralls
      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: go get github.com/modocache/gover

      # Testing
      #- run: ginkgo -r -cover -coverpkg=./... -trace -race
      #- run: gover
      #- run: goveralls -coverprofile=gover.coverprofile -service=circle-ci -repotoken=PzqT8p7uG5E7f2MwBoqeH1PgwZwxrKDja

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results