version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/mihailo-misic/company-resource-api

    environment:
      TEST_RESULTS: /tmp/test-results
      COVERALLS_TOKEN: yCn3klc8SDmcBsJmiov4DOGl5gLgdYlGq

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      # Getting dependencies
      - run: go get -v -t -d ./...
      - run: go get github.com/mattn/goveralls
      - run: go get github.com/onsi/ginkgo/ginkgo

      # Testing
      - run: ginkgo -r -cover -coverpkg=./... -trace -race -coverprofile=${TEST_RESULTS}/c.out
      - run:
          name: Run unit tests
          command: |
            trap "goveralls -coverprofile=${TEST_RESULTS}/c.out -service=circle-ci -repotoken=${COVERALLS_TOKEN}" EXIT | tee ${TEST_RESULTS}/c.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results